/* eslint-disable prettier/prettier */
import { MigrationInterface, QueryRunner } from "typeorm";

export class IncludeAdmSupportRole1747543867498 implements MigrationInterface {
    name = 'IncludeAdmSupportRole1747543867498'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "consultation" DROP CONSTRAINT "FK_f4018d1e2b5da78a190df93fdbf"`);
        await queryRunner.query(`CREATE TABLE "customer_support" ("id" SERIAL NOT NULL, "id_customer" integer NOT NULL, "email" character varying(60) NOT NULL, "phone" character varying(15) NOT NULL, "title" character varying(100) NOT NULL, "content" character varying(300) NOT NULL, "status" character varying(30) NOT NULL DEFAULT 'pending', "admResponsible" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cc864d06accbb228be3826432be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "adm" ("id" SERIAL NOT NULL, "name" character varying(80) NOT NULL, "email" character varying(254) NOT NULL, "password" character varying(255) NOT NULL, "role" character varying(3) NOT NULL DEFAULT 'adm', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0f5ee0a519c677c5237a33b9516" UNIQUE ("email"), CONSTRAINT "PK_d4dab02cf2667fc5b673741b322" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "consultant_support" ("id" SERIAL NOT NULL, "id_consultant" integer NOT NULL, "email" character varying(30) NOT NULL, "phone" integer NOT NULL, "title" character varying(100) NOT NULL, "content" character varying(300) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'pending', "admResponsible" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_898b147550f1bb588c1d470b149" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "schedule_exception" DROP COLUMN "unavaiable_time"`);
        await queryRunner.query(`ALTER TABLE "consultation" DROP COLUMN "id_consultant_specialty"`);
        await queryRunner.query(`ALTER TABLE "consultation" DROP COLUMN "appoinment_data"`);
        await queryRunner.query(`ALTER TABLE "schedule_exception" ADD "unavailable_time" TIME NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consultation" ADD "appoinment_date" date NOT NULL DEFAULT '2025-01-01'`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "role" character varying(4) NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "appellant" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "role" character varying(10) NOT NULL DEFAULT 'consultant'`);
        await queryRunner.query(`ALTER TABLE "schedule_exception" DROP COLUMN "date_exception"`);
        await queryRunner.query(`ALTER TABLE "schedule_exception" ADD "date_exception" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "schedule_exception" DROP COLUMN "reason"`);
        await queryRunner.query(`ALTER TABLE "schedule_exception" ADD "reason" character varying(45) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "schedule_consultant" ALTER COLUMN "status" SET DEFAULT 'disponível'`);
        await queryRunner.query(`ALTER TABLE "consultation" DROP CONSTRAINT "FK_2deb16fe0157da166d85f098755"`);
        await queryRunner.query(`ALTER TABLE "consultation" DROP CONSTRAINT "FK_5b3da1fb269f3a2685b18dbdd21"`);
        await queryRunner.query(`ALTER TABLE "consultation" ALTER COLUMN "id_customer" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "consultation" ALTER COLUMN "id_schedule_consultant" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "consultation" ALTER COLUMN "appoinment_time" SET DEFAULT '12:00:00'`);
        await queryRunner.query(`ALTER TABLE "consultation" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "consultation" ADD "status" character varying(15) DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "consultation" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "consultation" ADD "status" character varying(7) DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "name" character varying(60) NOT NULL DEFAULT 'NaN'`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "phone" character varying(15) NOT NULL DEFAULT 'NaN'`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "email" character varying(60) NOT NULL DEFAULT 'NaN'`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "UQ_fdb2f3ad8115da4c7718109a6eb" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "password" character varying(300) NOT NULL DEFAULT 'NaN'`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "status" character varying(15) NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "name" character varying(60) NOT NULL DEFAULT 'NaN'`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "cpf"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "cpf" character varying(11) NOT NULL DEFAULT 'NaN'`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "phone" character varying(15) NOT NULL DEFAULT 'NaN'`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP CONSTRAINT "UQ_0e86adbe5ab2b58254a76ccf698"`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "email" character varying(60) NOT NULL DEFAULT 'NaN'`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD CONSTRAINT "UQ_0e86adbe5ab2b58254a76ccf698" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "password" character varying(300) NOT NULL DEFAULT 'NaN'`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "profile_data"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "profile_data" character varying(800) NOT NULL DEFAULT 'NaN'`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "image_consultant"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "image_consultant" character varying(300) NOT NULL DEFAULT 'NaN'`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "status" character varying(15) NOT NULL DEFAULT 'inativo'`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "payment_plan"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "payment_plan" character varying(25) NOT NULL DEFAULT 'mensal'`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "about_specialties"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "about_specialties" character varying(700) NOT NULL DEFAULT 'NaN'`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "consultants_story"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "consultants_story" character varying(700) NOT NULL DEFAULT 'NaN'`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "consultations_carried_out"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "consultations_carried_out" integer DEFAULT '100'`);
        await queryRunner.query(`ALTER TABLE "consultation" ADD CONSTRAINT "FK_2deb16fe0157da166d85f098755" FOREIGN KEY ("id_customer") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultation" ADD CONSTRAINT "FK_5b3da1fb269f3a2685b18dbdd21" FOREIGN KEY ("id_schedule_consultant") REFERENCES "schedule_consultant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_support" ADD CONSTRAINT "FK_bf71e122be25d98fc8be654ee8c" FOREIGN KEY ("id_customer") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_support" ADD CONSTRAINT "FK_a930f96832c2356d71a5527c228" FOREIGN KEY ("admResponsible") REFERENCES "adm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultant_support" ADD CONSTRAINT "FK_5ceb071b24c84bbc989214651bd" FOREIGN KEY ("id_consultant") REFERENCES "consultant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultant_support" ADD CONSTRAINT "FK_1ca6a5329c23d7d4e209797cb8a" FOREIGN KEY ("admResponsible") REFERENCES "adm"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "consultant_support" DROP CONSTRAINT "FK_1ca6a5329c23d7d4e209797cb8a"`);
        await queryRunner.query(`ALTER TABLE "consultant_support" DROP CONSTRAINT "FK_5ceb071b24c84bbc989214651bd"`);
        await queryRunner.query(`ALTER TABLE "customer_support" DROP CONSTRAINT "FK_a930f96832c2356d71a5527c228"`);
        await queryRunner.query(`ALTER TABLE "customer_support" DROP CONSTRAINT "FK_bf71e122be25d98fc8be654ee8c"`);
        await queryRunner.query(`ALTER TABLE "consultation" DROP CONSTRAINT "FK_5b3da1fb269f3a2685b18dbdd21"`);
        await queryRunner.query(`ALTER TABLE "consultation" DROP CONSTRAINT "FK_2deb16fe0157da166d85f098755"`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "consultations_carried_out"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "consultations_carried_out" character varying`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "consultants_story"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "consultants_story" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "about_specialties"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "about_specialties" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "payment_plan"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "payment_plan" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "status" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "image_consultant"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "image_consultant" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "profile_data"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "profile_data" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP CONSTRAINT "UQ_0e86adbe5ab2b58254a76ccf698"`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD CONSTRAINT "UQ_0e86adbe5ab2b58254a76ccf698" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "phone" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "cpf"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "cpf" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "consultant" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "status" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "UQ_fdb2f3ad8115da4c7718109a6eb"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "phone" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consultation" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "consultation" ADD "status" character varying`);
        await queryRunner.query(`ALTER TABLE "consultation" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "consultation" ADD "status" character varying`);
        await queryRunner.query(`ALTER TABLE "consultation" ALTER COLUMN "appoinment_time" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "consultation" ALTER COLUMN "id_schedule_consultant" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "consultation" ALTER COLUMN "id_customer" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "consultation" ADD CONSTRAINT "FK_5b3da1fb269f3a2685b18dbdd21" FOREIGN KEY ("id_schedule_consultant") REFERENCES "schedule_consultant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultation" ADD CONSTRAINT "FK_2deb16fe0157da166d85f098755" FOREIGN KEY ("id_customer") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_consultant" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "schedule_exception" DROP COLUMN "reason"`);
        await queryRunner.query(`ALTER TABLE "schedule_exception" ADD "reason" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "schedule_exception" DROP COLUMN "date_exception"`);
        await queryRunner.query(`ALTER TABLE "schedule_exception" ADD "date_exception" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "consultant" DROP COLUMN "appellant"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "consultation" DROP COLUMN "appoinment_date"`);
        await queryRunner.query(`ALTER TABLE "schedule_exception" DROP COLUMN "unavailable_time"`);
        await queryRunner.query(`ALTER TABLE "consultation" ADD "appoinment_data" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consultation" ADD "id_consultant_specialty" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "schedule_exception" ADD "unavaiable_time" character varying NOT NULL`);
        await queryRunner.query(`DROP TABLE "consultant_support"`);
        await queryRunner.query(`DROP TABLE "adm"`);
        await queryRunner.query(`DROP TABLE "customer_support"`);
        await queryRunner.query(`ALTER TABLE "consultation" ADD CONSTRAINT "FK_f4018d1e2b5da78a190df93fdbf" FOREIGN KEY ("id_consultant_specialty") REFERENCES "consultant_specialty"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
